### ISSUE TITLE
Please archive this repo in a more permanent space

### ISSUE THREAD

**Issue by Daniel-Mietchen** [lucaswerkmeister/master-thesis#1]
E.g. Zenodo, as per https://www.software.ac.uk/blog/2016-09-26-making-code-citable-zenodo-and-github .

**Comment by lucaswerkmeister** [comment]
I’m not convinced that this random service I’ve never heard of before is inherently more permanent than GitHub, but if they say they’re using CERN’s data centre, sure, that sounds nice… I’ve signed up.

But apparently they only archive your repository for new releases, not existing ones? Seriously? I’m not about to create another release just because they apparently don’t expect authors to work on the repository before signing up for their service.

I guess I’ll try to [manually upload the data](https://twitter.com/zenodo_org/status/467385924532576256), if that’s really the only solution… jeez

**Comment by lucaswerkmeister** [comment]
Alright, now online at https://zenodo.org/record/2578259. Let me know if there are any problems.
